name: Lint

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install
      run: python -m pip install flake8
    - name: Lint with flake8
      run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
